name: GH Action for automated build
on: [pull_request, push]

jobs:
  build:
    name: Build for Android
    runs-on: macos-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
          
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'
        channel: 'master'
          
    - name: Decode Google Services
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_ANDROID }}
      run: echo $FIREBASE_ANDROID > app/google-services.json

    - run: flutter pub get
      
    - name: Build APK
      run: flutter build apk

#     - name: Test
#       run: flutter test test/widget_test.dart
